spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BzCoder/config-repo
          username: chengshuodage
          password: chengshuo.123
          basedir:  C:/Config/basedir
